/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerWorkArea;

import userinterface.SystemAdminWorkArea.*;
import Business.Customer.Customer;
import Business.Customer.CustomerDirectory;
import Business.EcoSystem;
import Business.Card.CardDirectory;
import Business.CardType.CardTypeList;
import Business.Merchant.MerchantDirectory;
import Business.Product.ProductDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author jayesh
 */
public class CustomerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem ecosystem;
    private CardTypeList cardTypeList;
    private MerchantDirectory merchantsDirectory;
    private CardDirectory cardDirectory;
    private UserAccount account;
    private ProductDirectory productDirectory;
    
    public CustomerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem ecosystem) {
        initComponents();
        this.account = account;
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.cardTypeList = ecosystem.getCardTypeList();
        this.cardDirectory = ecosystem.getCardDirectory();
        this.productDirectory = ecosystem.getProductDirectory();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnApplyCard = new javax.swing.JButton();
        btnManageShopping = new javax.swing.JButton();
        btnManageRedemption = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Welcome, ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 25, -1, -1));

        btnApplyCard.setText("Apply Card");
        btnApplyCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyCardActionPerformed(evt);
            }
        });
        jPanel2.add(btnApplyCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 178, 131, -1));

        btnManageShopping.setText("Manage Shopping");
        btnManageShopping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageShoppingActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageShopping, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 221, -1, -1));

        btnManageRedemption.setText("Redeem Points");
        btnManageRedemption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageRedemptionActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageRedemption, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 264, 131, -1));

        jLabel2.setText("<html> Total Amount Due -  <br/> Total Points - <br/> Points Redeemed -  </html>");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 59, 131, 62));

        add(jPanel2, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btnApplyCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyCardActionPerformed
       ApplyCardJPanel applyCard = new ApplyCardJPanel(userProcessContainer, account, ecosystem, cardTypeList);
       userProcessContainer.add("BankManagement",applyCard);
       CardLayout layout=(CardLayout)userProcessContainer.getLayout();
       layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnApplyCardActionPerformed

    private void btnManageShoppingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageShoppingActionPerformed
       ManageShoppingJPanel manageShopping = new ManageShoppingJPanel(userProcessContainer, account, ecosystem, productDirectory);
       userProcessContainer.add("manageShopping",manageShopping);
       CardLayout layout=(CardLayout)userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageShoppingActionPerformed

    private void btnManageRedemptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageRedemptionActionPerformed
       ManageMerchantJPanel mer = new ManageMerchantJPanel(userProcessContainer, ecosystem, merchantsDirectory);
       userProcessContainer.add("EmployeeManagement",mer);
       CardLayout layout=(CardLayout)userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageRedemptionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApplyCard;
    private javax.swing.JButton btnManageRedemption;
    private javax.swing.JButton btnManageShopping;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
