/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerWorkArea;

import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Card.CardDirectory;
import Business.CardType.CardTypeList;
import Business.Merchant.MerchantDirectory;
import Business.PaymentMethod.PaymentMethodDirectory;
import Business.Product.ProductDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author jayesh
 */
public class CustomerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem ecosystem;
    private CardTypeList cardTypeList;
    private MerchantDirectory merchantsDirectory;
    private CardDirectory cardDirectory;
    private UserAccount account;
    private ProductDirectory productDirectory;
    private Customer customer;
    private PaymentMethodDirectory paymentMethodDirectory;
    
    public CustomerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem ecosystem) {
        initComponents();
        this.account = account;
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.cardTypeList = ecosystem.getCardTypeList();
        this.cardDirectory = ecosystem.getCardDirectory();
        this.productDirectory = ecosystem.getProductDirectory();
        this.paymentMethodDirectory = ecosystem.getPaymentMethodDirectory();
        customer = ecosystem.getCustomerDirectory().getCustomer(account.getUsername());
        setText();
    }
    
    public void setText() {
        customer = ecosystem.getCustomerDirectory().getCustomer(account.getUsername());        
        String roha = "<html> <table style=\"border: 1px solid black;\"> > <tr style=\"border: 1px solid black;\"> > "
                + "<td style=\"border: 1px solid black;\"> Total Amount Due <td/><td style=\"border: 1px solid black;\"> "+customer.getExpenditure()+"  <td/> </tr> <tr style=\"border: 1px solid black;\"> > "
                + "<td style=\"border: 1px solid black;\"> Total Points <td/><td style=\"border: 1px solid black;\"> "+customer.getTotalPointsEarned()+"<td/> </tr> <tr style=\"border: 1px solid black;\"> >  "
                + "<td style=\"border: 1px solid black;\"> Points Redeemed <td/><td style=\"border: 1px solid black;\"> "+  customer.getPointsUsed()+"<td/> <tr/> </html>";        
        jLabel2.setText(roha);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnApplyCard = new javax.swing.JButton();
        btnManageShopping = new javax.swing.JButton();
        btnManageRedemption = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        payment1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Welcome ...!!!");

        btnApplyCard.setText("Manage Cards");
        btnApplyCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyCardActionPerformed(evt);
            }
        });

        btnManageShopping.setText("Manage Shopping");
        btnManageShopping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageShoppingActionPerformed(evt);
            }
        });

        btnManageRedemption.setText("Manage Redemption");
        btnManageRedemption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageRedemptionActionPerformed(evt);
            }
        });

        jLabel2.setText("<html> Total Amount Due -  <br/> Total Points - <br/> Points Redeemed -  </html>");

        payment1.setText("Manage Payment");
        payment1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payment1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnApplyCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnManageShopping, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                            .addComponent(btnManageRedemption)
                            .addComponent(payment1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel1)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnApplyCard, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(btnManageShopping, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnManageRedemption, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(payment1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        add(jPanel2, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btnApplyCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyCardActionPerformed
       ApplyCardJPanel applyCard = new ApplyCardJPanel(userProcessContainer, account, ecosystem, cardTypeList, customer);
       userProcessContainer.add("BankManagement",applyCard);
       CardLayout layout=(CardLayout)userProcessContainer.getLayout();
       layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnApplyCardActionPerformed

    private void btnManageShoppingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageShoppingActionPerformed
       ManageShoppingJPanel manageShopping = new ManageShoppingJPanel(userProcessContainer, account, ecosystem, productDirectory, customer);
       userProcessContainer.add("manageShopping",manageShopping);
       CardLayout layout=(CardLayout)userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageShoppingActionPerformed

    private void btnManageRedemptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageRedemptionActionPerformed
//       ManageMerchantJPanel mer = new ManageMerchantJPanel(userProcessContainer, ecosystem, merchantsDirectory);
       ManageRedemptionJPanel mer = new ManageRedemptionJPanel(userProcessContainer,account, ecosystem, merchantsDirectory, customer);
       userProcessContainer.add("manageVoucher",mer);
       CardLayout layout=(CardLayout)userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageRedemptionActionPerformed

    private void payment1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payment1ActionPerformed
        // TODO add your handling code here:
        ManagePaymentJPanel mer = new ManagePaymentJPanel(userProcessContainer,account, ecosystem, paymentMethodDirectory, customer);
       userProcessContainer.add("managePayment",mer);
       CardLayout layout=(CardLayout)userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_payment1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApplyCard;
    private javax.swing.JButton btnManageRedemption;
    private javax.swing.JButton btnManageShopping;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton payment1;
    // End of variables declaration//GEN-END:variables
}
