/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.Merchant.Merchant;
import Business.Merchant.MerchantDirectory;
import Business.EcoSystem;
import Business.Employee.EmployeeDirectory;
import Business.Role.MerchantRole;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author somnathsolaskar
 */
public class UpdateMerchantJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateMerchantJPanel
     */
     private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
    private Merchant merchant;
    private UserAccountDirectory userAccountDirectory;
    private MerchantDirectory merchantDirectory;
    
    public UpdateMerchantJPanel(JPanel userProcessContainer, EcoSystem ecoSystem,MerchantDirectory merchantDirectory, Merchant merchant) {
        initComponents();
          this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.merchant = merchant;
        this.merchantDirectory = ecoSystem.getMerchantDirectory();
        addre.setText(merchant.getAddress());
        bankName.setText(merchant.getName());
        contactNum.setText(merchant.getPhoneNumber());
        manager.setText(merchant.getManagerName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addre = new javax.swing.JTextField();
        manager = new javax.swing.JTextField();
        contactNum = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        bankName = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("UPDATE MERCHANT DETAILS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 28, 662, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Name :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 152, 59, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Address :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 207, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Manager :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 271, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Contact :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 342, -1, -1));
        add(addre, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 205, 149, -1));
        add(manager, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 269, 149, -1));

        contactNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactNumActionPerformed(evt);
            }
        });
        add(contactNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 340, 149, -1));

        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 415, -1, 38));

        bankName.setEditable(false);
        add(bankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 150, 149, -1));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/93634-2.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 75, 64, 58));
    }// </editor-fold>//GEN-END:initComponents

    private void contactNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactNumActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
         int res = validateInput();
        if(res == 1){
        }
        else{

        merchant.setAddress(addre.getText());
        merchant.setPhoneNumber(contactNum.getText());
        merchant.setManagerName(manager.getText());
        
        JOptionPane.showMessageDialog(null, "Merchant Profile Updated.");
        btnBackActionPerformed(null);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageMerchantJPanel mmjp = (ManageMerchantJPanel) component;
        mmjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed
    public int validateInput(){
    
        int flag = 0;
        
        
        if(addre.getText().isEmpty() || contactNum.getText().isEmpty() || manager.getText().isEmpty()) {
            flag = 1;
            JOptionPane.showMessageDialog(null, "Fields cannot be empty ! ");
            
        }
        
        
        if((!(Pattern.matches("(0/91)?[7-9][0-9]{9}",contactNum.getText())))){
            flag = 1;
            JOptionPane.showMessageDialog(null,"Please enter a valid contact number", "Error", JOptionPane.ERROR_MESSAGE);
        }
        return flag;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addre;
    private javax.swing.JTextField bankName;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTextField contactNum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField manager;
    // End of variables declaration//GEN-END:variables
}
